modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/CreativeMD/CMDCam/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="cmdcam"
    logoFile="cmdcam.png"
    version="2.0.20"
    displayName="CMDCam"
    displayURL="https://modrinth.com/mod/cmdcam"
    displayTest="IGNORE_SERVER_VERSION"
    authors="CreativeMD"
    description='''Create camera paths.'''

[[dependencies.cmdcam]]
    modId="forge"
    mandatory=true
    versionRange="[43.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cmdcam]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cmdcam]]
   modId="creativecore"
   mandatory=true
   ordering="NONE"
   side="BOTH"
   versionRange="2.11.27"

