modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/CreativeMD/CMDCam/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="cmdcam"
    logoFile="cmdcam.png"
    version="2.1.1"
    displayName="CMDCam"
    displayURL="https://modrinth.com/mod/cmdcam"
    authors="CreativeMD"
    description='''Create camera paths.'''

[[dependencies.cmdcam]]
    modId="forge"
    mandatory=true
    versionRange="[40.2.14,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cmdcam]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cmdcam]]
   modId="creativecore"
   mandatory=true
   ordering="NONE"
   side="BOTH"
   versionRange="2.11.5"

